version: "3"

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  start:
    desc: Start both backend API and frontend
    deps: [start-api, start-web]
    parallel: true
    cmds:
      - echo "Starting Agentic Support Copilot..."
      - echo "Backend - API at http://localhost:8000"
      - echo "Frontend - Web at http://localhost:3000"
      - echo "Both services started"

  start-api:
    desc: Start the FastAPI backend
    dir: apps/api
    cmds:
      - task start

  start-web:
    desc: Start the React frontend
    dir: apps/web
    cmds:
      - task start

  setup-supabase:
    desc: Interactive Supabase project setup and configuration
    dir: supabase
    cmds:
      - echo "🚀 Starting Supabase Project Setup..."
      - task setup

  seed-kb:
    desc: Seed Supabase knowledge base with sample articles
    dir: apps/api
    cmds:
      - echo "📚 Seeding knowledge base with sample articles..."
      - python scripts/setup_knowledge_base.py

  setup-app:
    desc: Setup Python backend dependencies and web frontend
    dir: apps
    cmds:
      - echo "🔧 Setting up Python backend..."
      - cd api && task setup
      - echo "🔧 Setting up Node.js frontend..."
      - cd web && task setup

  stop:
    desc: Stop all running services
    cmds:
      - echo "🛑 Stopping all services..."
      - task: stop-api
      - task: stop-web

  stop-api:
    desc: Stop the FastAPI backend
    dir: apps/api
    cmds:
      - task stop

  stop-web:
    desc: Stop the React frontend
    cmds:
      - pkill -f "vite\|npm run dev" || echo "No frontend process found"

  health:
    desc: Check health of all services
    cmds:
      - echo "🏥 Checking service health..."
      - task: health-api
      - task: health-web

  health-api:
    desc: Check API health
    cmds:
      - curl -f http://localhost:8000/health && echo "✅ API is healthy" || echo "❌ API is not responding"

  health-web:
    desc: Check frontend health
    cmds:
      - curl -f http://localhost:3000 > /dev/null 2>&1 && echo "✅ Frontend is running" || echo "❌ Frontend is not responding"

  dev:
    desc: Start all apps in development mode with debug logging
    cmds:
      - echo "🐛 Starting in development mode..."
      - task --parallel dev-api dev-web

  dev-api:
    desc: Start API in development mode
    dir: apps/api
    cmds:
      - task dev

  dev-web:
    desc: Start Web in development mode
    dir: apps/web
    cmds:
      - task dev

  docs:
    desc: Open documentation for all services
    cmds:
      - echo "📚 Opening documentation..."
      - open http://localhost:8000/docs
      - open http://localhost:3000

  clean:
    desc: Clean all generated files and dependencies
    cmds:
      - echo "🧹 Cleaning project..."
      - task: clean-api
      - task: clean-web

  clean-api:
    desc: Clean Python backend
    dir: apps/api
    cmds:
      - task clean

  clean-web:
    desc: Clean Node.js frontend
    dir: apps/web
    cmds:
      - task clean

  logs:
    desc: Show logs for all services
    cmds:
      - echo "📋 Recent logs:"
      - echo "Backend logs:"
      - task: logs-api
      - echo "Frontend logs:"
      - task: logs-web

  logs-api:
    desc: Show API logs
    dir: apps/api
    cmds:
      - task logs

  logs-web:
    desc: Show frontend logs
    dir: apps/web
    cmds:
      - task logs
